// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABfnB_DQi9qdJ6uH9UP_bLG00FwZ8u_MI',
    appId: '1:610954433913:web:f7ffc18a10dd88615fcba8',
    messagingSenderId: '610954433913',
    projectId: 'siloka-push-notif',
    authDomain: 'siloka-push-notif.firebaseapp.com',
    storageBucket: 'siloka-push-notif.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUFz77GY4hjoMFSAMk5kj2D4OqD8hybQM',
    appId: '1:610954433913:android:9925f4efdf8839c65fcba8',
    messagingSenderId: '610954433913',
    projectId: 'siloka-push-notif',
    storageBucket: 'siloka-push-notif.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2lXQWXIpEjSv5eGXVA36JUVX4Pn5SYzk',
    appId: '1:610954433913:ios:5be6f2c7ae3763805fcba8',
    messagingSenderId: '610954433913',
    projectId: 'siloka-push-notif',
    storageBucket: 'siloka-push-notif.appspot.com',
    iosClientId: '610954433913-aige8a0k3e7l2jpq2seaa8qrs01gi1ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.silokaSecurity',
  );
}
